CREATE TABLE ITENS_PEDIDOS( 
ID_ITENS SERIAL PRIMARY KEY, 
ID_PEDIDOS INT NOT NULL, 
ID_PRODUTOS INT NOT NULL, 
QUANTIDADE INT NOT NULL, 
PRECO_UNIT REAL NOT NULL, 
SUBTOTAL REAL NOT NULL, 
CONSTRAINT FK_PEDIDOS FOREIGN KEY ID_PEDIDOS REFERENCES PEDIDOS (ID_PEDIDOS),
CONSTRAINT FK_PRODUTOS FOREIGN KEY ID_PRODUTO REFERENCES PRODUTOS (ID_PRODUTO)
);

CREATE TABLE PRODUTOS( 
ID_PRODUTOS SERIAL PRIMARY KEY, 
NOME VARCHAR ( 100) NOT NULL, 
PRECO REAL NOT NULL ,WHERE  (PRECO IN (PRECO > 0)), 
ESTOQUE REAL NOT NULL DEFAULT 0 WHERE (ESTOQUE IN(ESTOQUE > 0 && ESTOQUE == 0 )), 
ATICO INT NOT NULL DEFAULT 0
);

CREATE TABLE PAGAMENTOS( 
ID_PAGAMENTO SERIAL PRIMARY KEY, 
ID_PEDIDOS INT NOT NULL, 
VALOR REAL NOT NULL WHERE (VALOR IN (VALOR > 0 && VALOR == 0)), 
DATA_PAGAMENTO DATE DEFAULT CURRENT_TIMESTAMP, 
FORMA VARCHAR (10) CHECK (FORMA IN ('PIX', 'CARTÃO', 'BOLETO')) NOT NULL,
CONSTRAINT FK_PEDIDO FOREIGN KEY ID_PEDIDO REFERENCES PEDIDOS (ID_PEDIDO)
);

CREATE TABLE PEDIDOS ( 
ID_PEDIDO SERIAL PRIMARY KEY, 
ID_CLIENTE INT NOT NULL, 
DATA_PEDIDO DATE NOT NULL DEFAULT CURRENT_TIMESTAMP, 
STATUS_PEDIDOS INT NOT NULL CHECK (STATUS_PEDIDOS IN ('ABERTO', 'FECHADO', 'CANCELADO')) DEFAULT 'ABERTO', 
TOTAL REAL NOT NULL DEFAULT 0,
CONSTRAINT FK_CLIENTE FOREIGN KEY ID_CLIENTE REFERENCES CLIENTES (ID_CLIENTE)
); 
INSERT INTO PEDIDOS (ID_CLIENTE,DATA_PEDIDO, STATUS_PEDIDOS, TOTAL)VALUES( 
1
'2085-08-20', 
'ABERTO', 
200.00
), 
(
5
'2025-09-31', 
'FECHADO', 
20.00
), 
(
4
'2025-08-27',
'FECHADO', 
'2050-05-20',
20.00
); 
( 
5, 
'FECHADO', 
'2025-02-20', 
300.00
),
(
4, 
'FECHADO', 
'2029-04-09',
40.00
), 
(
1, 
'ABERTO', 
'2090-04-09',
40.00
), 
(
2, 
'ABERTO', 
'2100-04-09',
400.00
),
(
2, 
'ABERTO', 
'2100-04-09',
900.00
)


CREATE TABLE CLIENTES( 
ID_CLIENTE SERIAL PRIMARY KEY, 
NOME VARCHAR (100) NOT NULL, 
EMAIL TEXT NOT NULL, 
STATUS_CLIENTE INT NOT NULL CHECK (STATUS_CLIENTE IN ('STANDARD', 'GOLD', 'PLATINUM') DEFAULT 'STANDARD', 
DATA_CADASTRO DATE NOT NULL DEFAULT CURRENT_DATE, 
SALDO_CREDITO REAL NOT NULL DEFAULT 'ZERO'
);

INSERT INTO CLIENTES(
NOME, 
EMAIL, 
STATUS_CLIENTE,
SALDO_CREDITO)
VALUES ('JHEFFERSON','JHEFFESONMATHEUS2017@GMAIL.COM','STANDARD',100.40), 
('MARIA','MARIA@EXEMPLO.COM','GOLD',200.50), 
('JOAO','JOAO@EXEMPLO.COM','PLATINUM',300.60), 
('ANA','ANA@EXEMPLO.COM','STANDARD',150.00), 
('PEDRO','PEDRO@EXEMPLO.COM','GOLD',250.00);