CREATE TABLE PAIS( 
IDPAIS SERIAL PRIMARY KEY, 
NOME VARCHAR (100),
SIGLA VARCHAR (10)
);

CREATE TABLE ESTADO ( 
IDESTADO SERIAL PRIMARY KEY, 
NOME VARCHAR (100), 
SIGLA VARCHAR (10), 
IDPAIS INT, 
CONSTRAINT FK_IDPAIS FOREIGN KEY (IDPAIS) REFERENCES PAIS (IDPAIS)
);

CREATE TABLE CIDADE ( 
IDCIDADE SERIAL PRIMARY KEY, 
NOME VARCHAR (100), 
INSCRICAOSTADUAL INT, 
IDESTADOS INT,
CONSTRAINT FH_ESTADOS FOREIGN KEY (IDESTADOS) REFERENCES ESTADO (IDESTADO)
);

CREATE TABLE PARCEIRO( 
IDPARCEIRO SERIAL PRIMARY KEY, 
DOCUMENTO DOUBLE, 
NOME VARCHAR (255), 
NOMEFANTASIA VARCHAR (255) NOT NULL, 
OBSERVACAO VARCHAR (255) NOT NULL, 
IDNATIVA BIT
);

CREATE TABLE USUARIO( 
IDUSUARIO SERIAL PRIMARY KEY, 
NOME VARCHAR (255), 
EMAIL VARCHAR (255) NOT NULL, 
OBSERVACAO VARCHAR (255)NOT NULL ,
IDNATIVO BIT
);

CREATE TABLE TELEFONE ( 
IDTELEFONE SERIAL PRIMARY KEY, 
NUMERO INTEGER (10), 
IDUSUARIO INT, 
IDPARCEIRO INT, 
CONSTRAINT FK_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO), 
CONSTRAINT FK_IDPARCEIRO FOREIGN KEY (IDPARCEIRO) REFERENCES PARCEIRO (IDPARCEIRO), 
IDNATIVO BIT
);

CREATE TABLE ENDERECO( 
IDENDERENCO SERIAL PRIMARY KEY, 
LOGRADOURA VARCHAR (255), 
NUMERO INTEGER (10), 
CEP INTEGER (10), 
COMPLEMENTO VARCHAR (255) NOT NULL, 
IDPARCEIRO INT, 
IDUSUARIO INT, 
IDCIDADE INT
IDNATIVO BIT,
CONSTRAINT FK_IDPARCEIRO FOREIGN KEY (IDPARCEIRO) REFERENCES PARCEIRO (IDPARCEIRO), 
CONSTRAINT FK_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO), 
CONSTRAINT FK_IDCIDADE FOREIGN KEY (IDCIDADE) REFERENCES CIDADE (IDCIDADE)
);

CREATE TABLE PRODUTO ( 
IDPRODUTOS SERIAL PRIMARY KEY, 
CODIGO INTEGER (10), 
DESCRICAO VARCHAR (255), 
OBSERVACAO VARCHAR (255), 
PESO DOUBLE (10)
);

CREATE TABLE TABELAPRECO(
IDTABELAPRECO SERIAL PRIMARY KEY, 
DESCREÇÃO VARCAHR (200), 
DESCONTOMAXIMO DOUBLE (10), 
CODIGO INTEGER (10), 
INCIOVIGENDA DATE, 
FINVIGENCIA DATE, ]
IDNATIVO BIT
);

CREATE TABLE TABELAPRECOPRODUTO(
IDTABELAPRECOPRODUTO SERIAL PRIMARY KEY, 
IDTABELAPRECO INT, 
IDPRODUTO INT, 
PRECO DOUBLE, 
CONSTRAINT FK_IDTABELAPRECO FOREIGN KEY (IDTABELAPRECO) REFERENCES TABELAPRECO(IDTABELAPRECO), 
CONSTRAINT FK_IDPRODUTOS FOREIGN KEY (IDPRODUTOS) REFERENCES PRODUTOS (IDPRODUTOS)
);

CREATE TABLE CONDICAOPAGAMENTO( 
IDCONDICAOPAGAMENTO SERIAL PRIMARY KEY, 
DESCRICAO VARCHAR (255), 
CODIGO INTEGER (10), 
OBSERVACAO VARCHAR (255)
);

CREATE TABLE PEDIDO( 
IDPEDIDOS SERIAL PRIMARY KEY, 
NUMERO INTEGER (10), 
VATORTOTAL INTEGER (10), 
QUANTIDADEPRODUTOS DOUBLE (10), 
OBSERVACAO VARCHAR (255), 
IDTABELAPRECO INT, 
IDCONDICAOPAGAMENTO INT, 
IDPARCEIRO INT, 
IDUSUARIO INT, 
DATA TIMESTAMP
CONSTRAINT FK_IDTABELAPRECO FOREIGN KEY (IDTABELAPRECO) REFERENCES TABELAPRECO (IDTABELAPRECO);
CONSTRAINT FK_IDCONDICAOPAGAMENTO FOREIGN KEY (IDCONDICAOPAGAMENTO) REFERENCES CONDICAODEPAGAMENTO (IDCONDICAOPAGAMENTO), 
CONSTRAINT FK_IDPARCEIRO FOREIGN KEY (IDPARCEIRO) REFERENCES PARCEIRO (IDPARCEIRO), 
CONSTRAINT FK_IDUSUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);